/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProntuariosRouteImport } from './routes/_app/prontuarios'
import { Route as AppPacientesRouteImport } from './routes/_app/pacientes'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppConsultasRouteImport } from './routes/_app/consultas'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppPacientesIndexRouteImport } from './routes/_app/pacientes/index'
import { Route as AppPacientesNovoRouteImport } from './routes/_app/pacientes/novo'
import { Route as AppPacientesIdRouteImport } from './routes/_app/pacientes/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProntuariosRoute = AppProntuariosRouteImport.update({
  id: '/prontuarios',
  path: '/prontuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultasRoute = AppConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPacientesRoute,
} as any)
const AppPacientesNovoRoute = AppPacientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppPacientesRoute,
} as any)
const AppPacientesIdRoute = AppPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/consultas': typeof AppConsultasRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/prontuarios': typeof AppProntuariosRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
  '/pacientes/novo': typeof AppPacientesNovoRoute
  '/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/consultas': typeof AppConsultasRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/prontuarios': typeof AppProntuariosRoute
  '/': typeof AppIndexRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
  '/pacientes/novo': typeof AppPacientesNovoRoute
  '/pacientes': typeof AppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/consultas': typeof AppConsultasRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/pacientes': typeof AppPacientesRouteWithChildren
  '/_app/prontuarios': typeof AppProntuariosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pacientes/$id': typeof AppPacientesIdRoute
  '/_app/pacientes/novo': typeof AppPacientesNovoRoute
  '/_app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/consultas'
    | '/financeiro'
    | '/pacientes'
    | '/prontuarios'
    | '/pacientes/$id'
    | '/pacientes/novo'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agenda'
    | '/configuracoes'
    | '/consultas'
    | '/financeiro'
    | '/prontuarios'
    | '/'
    | '/pacientes/$id'
    | '/pacientes/novo'
    | '/pacientes'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agenda'
    | '/_app/configuracoes'
    | '/_app/consultas'
    | '/_app/financeiro'
    | '/_app/pacientes'
    | '/_app/prontuarios'
    | '/_app/'
    | '/_app/pacientes/$id'
    | '/_app/pacientes/novo'
    | '/_app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prontuarios': {
      id: '/_app/prontuarios'
      path: '/prontuarios'
      fullPath: '/prontuarios'
      preLoaderRoute: typeof AppProntuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultas': {
      id: '/_app/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof AppConsultasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/': {
      id: '/_app/pacientes/'
      path: '/'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppPacientesRoute
    }
    '/_app/pacientes/novo': {
      id: '/_app/pacientes/novo'
      path: '/novo'
      fullPath: '/pacientes/novo'
      preLoaderRoute: typeof AppPacientesNovoRouteImport
      parentRoute: typeof AppPacientesRoute
    }
    '/_app/pacientes/$id': {
      id: '/_app/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AppPacientesIdRouteImport
      parentRoute: typeof AppPacientesRoute
    }
  }
}

interface AppPacientesRouteChildren {
  AppPacientesIdRoute: typeof AppPacientesIdRoute
  AppPacientesNovoRoute: typeof AppPacientesNovoRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
}

const AppPacientesRouteChildren: AppPacientesRouteChildren = {
  AppPacientesIdRoute: AppPacientesIdRoute,
  AppPacientesNovoRoute: AppPacientesNovoRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
}

const AppPacientesRouteWithChildren = AppPacientesRoute._addFileChildren(
  AppPacientesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConsultasRoute: typeof AppConsultasRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppPacientesRoute: typeof AppPacientesRouteWithChildren
  AppProntuariosRoute: typeof AppProntuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConsultasRoute: AppConsultasRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppPacientesRoute: AppPacientesRouteWithChildren,
  AppProntuariosRoute: AppProntuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
